export interface InterpreterSkills {
    primary_language: any,
    secondary_language: any,
    interpreter_id: any,
    documents: any,
    other_title: any,
    community_doc: any,
    conference_doc: any,
    court_doc: any,
    credential_doc: any,
    equipment_doc: any,
    legal_doc: any,
    simult_open: any,
    other_doc: any,
}
